# Generated by Django 3.0.1 on 2021-04-03 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, null=True, unique=True)),
                ('slug', models.SlugField(default='')),
                ('photo', models.ImageField(null=True, upload_to='blogs_photos/')),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
