# Generated by Django 3.0.1 on 2020-12-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
    ]
