# Generated by Django 3.0.1 on 2021-04-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0005_auto_20210402_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ask_questions',
        ),
        migrations.DeleteModel(
            name='AskQuestions',
        ),
    ]
