# Generated by Django 3.0.1 on 2020-12-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0005_auto_20201220_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='product_photos/'),
        ),
    ]
