# Generated by Django 3.0.1 on 2020-12-21 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0006_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
