# Generated by Django 3.0.1 on 2021-04-02 05:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productMS', '0006_auto_20210402_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(default='', null=True)),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ask_questions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productMS.AskQuestions'),
        ),
    ]
