# Generated by Django 3.0.1 on 2021-04-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0007_auto_20210402_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ask_questions',
        ),
        migrations.AddField(
            model_name='askquestions',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productMS.Product'),
        ),
    ]
