# Generated by Django 3.0.1 on 2020-12-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0007_auto_20201221_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='banner_photos/')),
                ('url', models.URLField()),
            ],
        ),
    ]
