# Generated by Django 3.0.1 on 2020-12-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0008_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
