# Generated by Django 3.0.1 on 2020-12-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0009_banner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(default='#', null=True),
        ),
    ]
