# Generated by Django 3.0.1 on 2020-12-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0010_auto_20201221_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(default='#', max_length=200, null=True),
        ),
    ]
