# Generated by Django 3.0.1 on 2021-04-02 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0010_auto_20210402_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='productMS.Product'),
        ),
    ]
