# Generated by Django 3.0.1 on 2020-12-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0011_auto_20201221_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
