# Generated by Django 3.0.1 on 2021-04-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0013_product_favourites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
