# Generated by Django 3.0.1 on 2021-04-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productMS', '0014_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.BooleanField(default=0),
        ),
    ]
