# Generated by Django 3.0.1 on 2020-10-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMS', '0003_auto_20201021_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
