# Generated by Django 3.0.1 on 2020-10-25 04:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userMS', '0005_emailverfication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerfication',
            new_name='EmailVerification',
        ),
    ]
